### ISSUE TITLE
Erreur lors de création commande en BO

### ISSUE THREAD

**Issue by MaxBoBiD** [MAD-I-T/Magento2-AtosSips-Sherlock-LCL#1]
Bonjour, lors de la création d'une commande en BO, les produits ne s'ajoute pas et le message suivant apparaît : 
 exception(s):
Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'Madit_Atos::atos/form/standard.phtml' in module: 'Madit_Atos' block's name: 'atos_standard'

Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'Madit_Atos::atos/form/standard.phtml' in module: 'Madit_Atos' block's name: 'atos_standard'

**Comment by seyuf** [comment]
Bonjour @MaxBoBiD ,

Je viens de régler le souci normalement, je te laisse tester et me dire si c'est ok ?
Au passage, pour l'instant, le module ne supporte pas le paiement au travers du Backend.
Néanmoins, tu pourras créer une commande au travers du BO en choisissant sherlock comme moyen de paiement, mais il faudra finaliser la commande en mode offline en passant par les invoices.

Cdlt

**Comment by MaxBoBiD** [comment]
Bonjour,
ok ca marche
Merci
