### ISSUE TITLE
Gateway Callback is a POST request to Magento that changes session ID

### ISSUE THREAD

**Issue by gulshankumar** [MAD-I-T/Magento2-AtosSips-Sherlock-LCL#4]
We are facing issue with payment gateway. When payment done at gateway and returning back to the store, it log out the customer and result in no success page.

The issue is in callback request, Callback request I a POST request, and browser doesn't send user's session cookie due to update cookie policy and Magento send a new session ID that misleads browser to a different session. And use gets logged out.

**Comment by seyuf** [comment]
Hi @gulshankumar , yep i am aware of this cookie issue.
That said, im kinda restricted time wise lately... In any case, i'll do my best to fix this by the end of next week.

**Comment by seyuf** [comment]
@gulshankumar  https://support.magento.com/hc/en-us/articles/360049032952-Customers-get-logged-out-or-lose-cart-content-on-Magento-storefront

**Comment by seyuf** [comment]
@gulshankumar the issue should be fixed, feel free to give some feedback.
